export let listaDeCidades = [ 
    'Americana',
    'Aparecida',
    'Atibaia',
    'Caçapava',
    'Campinas',
    'Campos do Jordão',
    'Cenário - Lorena',
    'Cruzeiro',
    'Cunha',
    'Guaratinguetá',
    'Guarulhos',
    'Itajubá',
    'Jundiaí',
    'Limeira',
    'Lorena',
    'Mogi das Cruzes',
    'Mogi Guaçu',
    'Mogi Mirim',
    'Pindamonhangaba',
    'Piracicaba',
    'Rio de Janeiro',
    'Santos',
    'Santo André',
    'São Bernardo',
    'São Caetano',
    'São Paulo',
    'São José dos Campos',
    'Sorocaba',
    'Taubaté'
]